### ISSUE TITLE
git stree pull checks completely replaces the content of the repo's root dir

### ISSUE THREAD

**Issue by thomaslevesque** [deliciousinsights/git-stree#40] opened 2015-07-23 16:42 UTC
I have a project with a structure similar to this:

```
main
│   .gitignore
│
└───src
    ├───app
    └───common
        ├───sub1
        │       blabla1
        │
        └───sub2
                blabla2
```
sub1 and sub2 are subtrees created with `git stree add`, here's their configuration:

```
[remote "stree-sub1"]
        url = http://(redacted)/(redacted)/sub1.git
        fetch = +refs/heads/master:refs/remotes/stree-sub1/master
[stree "sub1"]
        prefix = src/common/sub1
        branch = master
        latest-sync = bd68a0d

[remote "stree-sub2"]
        url = http://(redacted)/(redacted)/sub2.git
        fetch = +refs/heads/master:refs/remotes/stree-sub2/master
[stree "sub2"]
        prefix = src/common/sub2
        branch = master
        latest-sync = fa24b72
```

When I pull from sub2 to get the latest changes, it replaces EVERYTHING in my root dir with the content of sub2, so I end up with this:

```
main
    blabla2
```

Oops!

**Comment by thomaslevesque** [comment] 2015-07-23 17:05
If I try to pull manually as described in [your article](https://medium.com/@porteneuve/mastering-git-subtrees-943d29a798ec):

```
git fetch sub2
git merge -s subtree --squash stree-sub2/master
```
I get the same result.

If I use the recursive strategy with an explicit prefix instead:

```
git fetch sub2
git merge -X subtree=src/common/sub2 --squash stree-sub2/master
```

It writes the files to the right places, but I get conflicts on files that I didn't modify in main (same as #39)

**Comment by thomaslevesque** [comment] 2015-07-24 09:01
BTW, shouldn't git-stree  use `-X subtree=...` rather than `-s subtree`? My understanding is that they're equivalent when `-s subtree` works normally, but specifying the subtree prefix explicitly prevents the problem described above.

**Comment by mittwinter** [comment] 2015-09-24 16:19
I just ran into exactly the same situation using git stree pull [stree-name] with current HEAD. Any progress/ideas for this?

I would also gladly provide more details if needed or test any patches.

**Comment by mittwinter** [comment] 2015-09-24 16:48
Actually, I just found pull request #32 which sounded related, and after fetching it in my local git-stree repository by:
$ git fetch origin pull/32/head:mergefix
$ git checkout mergefix

I was able to pull the changes in the stree, but with conflicts. However,
$ git stree pull [stree-name] -Xtheirs
finally worked.

**Comment by tdd** [comment] 2015-12-31 14:03
The `-Xtheirs` option is not an all-fitting solution however, as this erases any local change you would have done to files changed in the stree's upstream as well. Working on a more general solution. Marking this as dup of #22 wrt root causes, so closing it here.

**Closed by tdd** 2015-12-31 14:03 UTC
